"""create_game_blueprints

Revision ID: 223922c110c3
Revises: d3ef12345678
Create Date: 2026-06-28 10:52:51.635667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '223922c110c3'
down_revision: Union[str, None] = 'd3ef12345678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_blueprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative_direction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('art_style_direction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('npc_archetypes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('npc_memory_design', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('level_design_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quest_hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unity_runtime_preview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('game_project_id', sa.String(length=100), server_default='default_project', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_blueprints_game_project_id'), 'game_blueprints', ['game_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_blueprints_game_project_id'), table_name='game_blueprints')
    op.drop_table('game_blueprints')
    # ### end Alembic commands ###
