"""create_graph_tables

Revision ID: 585f2df93d8f
Revises: 
Create Date: 2026-06-16 17:31:01.864256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '585f2df93d8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_ingests',
    sa.Column('validation_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason_blocked', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text("now() + interval '1 hour'"), nullable=False),
    sa.PrimaryKeyConstraint('validation_id')
    )
    op.create_table('relationship_type_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rel_type', sa.String(length=50), nullable=False),
    sa.Column('allowed_source_type', sa.String(length=50), nullable=False),
    sa.Column('allowed_target_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rel_type', 'allowed_source_type', 'allowed_target_type', name='uq_taxonomy_rule')
    )
    op.create_table('world_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_entity_slug')
    )
    op.create_table('consistency_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validation_id', sa.UUID(), nullable=False),
    sa.Column('override_applied_by', sa.String(length=100), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=False),
    sa.Column('override_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['validation_id'], ['pending_ingests.validation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_entity_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('importance_score', sa.Integer(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['world_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'version', name='uq_entity_version')
    )
    op.create_index('ix_active_entity_versions', 'world_entity_versions', ['entity_id'], unique=False, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_index('ix_entities_temporal', 'world_entity_versions', ['entity_id', 'valid_from', 'valid_to'], unique=False)
    op.create_index('uq_active_entity_version', 'world_entity_versions', ['entity_id'], unique=True, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_table('world_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('rel_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['world_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['world_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'rel_type', 'version', name='uq_relationship_version')
    )
    op.create_index('ix_active_relationship_source', 'world_relationships', ['source_id'], unique=False, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_index('ix_active_relationship_target', 'world_relationships', ['target_id'], unique=False, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_index('ix_relationships_temporal', 'world_relationships', ['source_id', 'target_id', 'valid_from', 'valid_to'], unique=False)
    op.create_index('uq_active_relationship', 'world_relationships', ['source_id', 'target_id', 'rel_type'], unique=True, postgresql_where=sa.text('valid_to IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_relationship', table_name='world_relationships', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_index('ix_relationships_temporal', table_name='world_relationships')
    op.drop_index('ix_active_relationship_target', table_name='world_relationships', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_index('ix_active_relationship_source', table_name='world_relationships', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_table('world_relationships')
    op.drop_index('uq_active_entity_version', table_name='world_entity_versions', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_index('ix_entities_temporal', table_name='world_entity_versions')
    op.drop_index('ix_active_entity_versions', table_name='world_entity_versions', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_table('world_entity_versions')
    op.drop_table('consistency_overrides')
    op.drop_table('world_entities')
    op.drop_table('relationship_type_rules')
    op.drop_table('pending_ingests')
    # ### end Alembic commands ###
