"""add_materialization_manifest

Revision ID: 655148f8d099
Revises: 223922c110c3
Create Date: 2026-07-01 10:50:24.986335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '655148f8d099'
down_revision: Union[str, None] = '223922c110c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_blueprints', sa.Column('materialization_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_blueprints', 'materialization_manifest')
    # ### end Alembic commands ###
