"""create_generated_quests

Revision ID: cb61e6326352
Revises: b733cf0567e9
Create Date: 2026-06-20 10:59:48.168353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb61e6326352'
down_revision: Union[str, None] = 'b733cf0567e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'generated_quests',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('npc_slug', sa.String(length=100), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('difficulty', sa.String(length=50), nullable=False, server_default='Medium'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['npc_slug'], ['npc_profiles.slug'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_quests_created_at'), 'generated_quests', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_quests_npc_slug'), 'generated_quests', ['npc_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_quests_npc_slug'), table_name='generated_quests')
    op.drop_index(op.f('ix_generated_quests_created_at'), table_name='generated_quests')
    op.drop_table('generated_quests')
    # ### end Alembic commands ###

