"""project scope docs relationships

Revision ID: d3ef12345678
Revises: 5c8a66009c44
Create Date: 2026-06-22 00:01:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ef12345678'
down_revision: Union[str, None] = '5c8a66009c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # 1. Add/normalize game_project_id on documents
    columns = [c['name'] for c in inspector.get_columns('documents')]
    if 'game_project_id' not in columns:
        op.add_column('documents', sa.Column('game_project_id', sa.String(length=100), nullable=True))
    op.execute("UPDATE documents SET game_project_id = 'default_project' WHERE game_project_id IS NULL")
    op.alter_column('documents', 'game_project_id', existing_type=sa.String(length=100), nullable=False, server_default='default_project')

    # 2. Add/normalize game_project_id on world_relationships
    columns = [c['name'] for c in inspector.get_columns('world_relationships')]
    if 'game_project_id' not in columns:
        op.add_column('world_relationships', sa.Column('game_project_id', sa.String(length=100), nullable=True))

    # 3. Validation check before backfilling world_relationships
    # Verify both source and target exist
    res = bind.execute(sa.text("""
        SELECT wr.id, wr.source_id, wr.target_id
        FROM world_relationships wr
        LEFT JOIN world_entities s ON wr.source_id = s.id
        LEFT JOIN world_entities t ON wr.target_id = t.id
        WHERE s.id IS NULL OR t.id IS NULL
    """)).fetchall()
    if res:
        raise RuntimeError(f"Abort migration: World relationships referencing non-existent entities: {res}")

    # Verify source project equals target project
    res = bind.execute(sa.text("""
        SELECT wr.id, wr.source_id, wr.target_id, s.game_project_id as src_proj, t.game_project_id as tgt_proj
        FROM world_relationships wr
        JOIN world_entities s ON wr.source_id = s.id
        JOIN world_entities t ON wr.target_id = t.id
        WHERE s.game_project_id != t.game_project_id
    """)).fetchall()
    if res:
        raise RuntimeError(f"Abort migration: Cross-project relationships detected: {res}")

    # 4. Backfill world_relationships.game_project_id from source entity
    bind.execute(sa.text("""
        UPDATE world_relationships wr
        SET game_project_id = s.game_project_id
        FROM world_entities s
        WHERE wr.source_id = s.id AND wr.game_project_id IS NULL
    """))
    # Fallback to default_project if any records are left empty
    op.execute("UPDATE world_relationships SET game_project_id = 'default_project' WHERE game_project_id IS NULL")
    op.alter_column('world_relationships', 'game_project_id', existing_type=sa.String(length=100), nullable=False, server_default='default_project')

    # 5. Drop old single-column foreign keys on world_relationships
    fks = [fk['name'] for fk in inspector.get_foreign_keys('world_relationships')]
    # Handle standard and SQLAlchemy autogenerated names
    for fk in fks:
        if fk in ['world_relationships_source_id_fkey', 'world_relationships_target_id_fkey'] or 'source_id' in fk or 'target_id' in fk:
            op.drop_constraint(fk, 'world_relationships', type_='foreignkey')

    # 6. Create uq_entity_project_id on world_entities if not exists
    uniques = [u['name'] for u in inspector.get_unique_constraints('world_entities')]
    if 'uq_entity_project_id' not in uniques:
        op.create_unique_constraint('uq_entity_project_id', 'world_entities', ['game_project_id', 'id'])

    # 7. Create composite foreign keys on world_relationships
    op.create_foreign_key(
        'fk_world_relationships_source',
        'world_relationships',
        'world_entities',
        ['game_project_id', 'source_id'],
        ['game_project_id', 'id'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_world_relationships_target',
        'world_relationships',
        'world_entities',
        ['game_project_id', 'target_id'],
        ['game_project_id', 'id'],
        ondelete='CASCADE'
    )

    # 8. Create project-scoped indexes for tables owned by this migration
    tables_to_index = [
        "documents",
        "world_relationships"
    ]
    for table in tables_to_index:
        idx_name = f'ix_{table}_game_project_id'
        indexes = [idx['name'] for idx in inspector.get_indexes(table)]
        if idx_name not in indexes:
            op.create_index(idx_name, table, ['game_project_id'], unique=False)


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # 1. Drop project-scoped indexes owned by this migration
    tables_to_index = [
        "documents",
        "world_relationships"
    ]
    for table in tables_to_index:
        idx_name = f'ix_{table}_game_project_id'
        indexes = [idx['name'] for idx in inspector.get_indexes(table)]
        if idx_name in indexes:
            op.drop_index(idx_name, table_name=table)

    # 2. Drop composite foreign keys
    fks = [fk['name'] for fk in inspector.get_foreign_keys('world_relationships')]
    if 'fk_world_relationships_source' in fks:
        op.drop_constraint('fk_world_relationships_source', 'world_relationships', type_='foreignkey')
    if 'fk_world_relationships_target' in fks:
        op.drop_constraint('fk_world_relationships_target', 'world_relationships', type_='foreignkey')

    # 3. Drop uq_entity_project_id unique constraint
    uniques = [u['name'] for u in inspector.get_unique_constraints('world_entities')]
    if 'uq_entity_project_id' in uniques:
        op.drop_constraint('uq_entity_project_id', 'world_entities', type_='unique')

    # 4. Re-create old single-column foreign keys
    op.create_foreign_key(
        'world_relationships_source_id_fkey',
        'world_relationships',
        'world_entities',
        ['source_id'],
        ['id'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'world_relationships_target_id_fkey',
        'world_relationships',
        'world_entities',
        ['target_id'],
        ['id'],
        ondelete='CASCADE'
    )

    # 5. Drop game_project_id columns
    columns = [c['name'] for c in inspector.get_columns('world_relationships')]
    if 'game_project_id' in columns:
        op.drop_column('world_relationships', 'game_project_id')

    columns = [c['name'] for c in inspector.get_columns('documents')]
    if 'game_project_id' in columns:
        op.drop_column('documents', 'game_project_id')
